# Generated by Django 5.1.7 on 2026-04-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Filial nomi')),
                ('city', models.CharField(max_length=255, verbose_name='Shahar')),
                ('cash_desk_count', models.PositiveIntegerField(default=0)),
                ('kitchen_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.CharField(default='RESTERP CAFE', max_length=255, verbose_name='Sarlavha matni')),
                ('footer_text', models.CharField(default='Xaridingiz uchun rahmat!', max_length=255, verbose_name='Pastki matn')),
                ('printer_name', models.CharField(default='Epson TM-T20', max_length=255, verbose_name='Printer')),
                ('auto_print', models.BooleanField(default=True, verbose_name='Avto chiqarish')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderFlowSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_send_to_kitchen', models.BooleanField(default=True, verbose_name='Ofitsiant → Oshxona avtomatik')),
                ('notify_when_ready', models.BooleanField(default=True, verbose_name='Tayyor bo‘lsa signal berish')),
                ('show_payment_button', models.BooleanField(default=True, verbose_name='Hisob so‘rash tugmasi ko‘rinsin')),
                ('enable_served_stage', models.BooleanField(default=False, verbose_name='Taom berildi bosqichi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Restoran nomi')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_percent', models.PositiveIntegerField(default=12, verbose_name='QQS (%)')),
                ('service_percent', models.PositiveIntegerField(default=10, verbose_name='Servis haqi (%)')),
                ('calculation_type', models.CharField(choices=[('auto', 'Avtomatik'), ('manual', 'Qo‘lda')], default='auto', max_length=10, verbose_name='Hisoblash turi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
