# Generated by Django 5.1.7 on 2026-04-03 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'Yangi'), ('COOKING', 'Tayyorlanmoqda'), ('READY', 'Tayyor'), ('CANCELLED', 'Bekor qilindi')], default='NEW', help_text='Oshxona jarayon holati.', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='Oshxona tayyorlashni boshlagan vaqt.', null=True)),
                ('ready_at', models.DateTimeField(blank=True, help_text='Taom tayyor bo‘lgan vaqt.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Ticket yaratilgan vaqt.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Oxirgi yangilanish.')),
                ('order', models.OneToOneField(help_text='Bog‘langan buyurtma.', on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_ticket', to='order.order')),
                ('sent_by', models.ForeignKey(blank=True, help_text='Ticketni yuborgan xodim.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_kitchen_tickets', to='employee.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='kitchen_kit_status_e5512a_idx'), models.Index(fields=['created_at'], name='kitchen_kit_created_055fec_idx')],
            },
        ),
    ]
