# Generated by Django 4.2.7 on 2026-03-14 05:54

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('mixed', 'Aralash')], help_text='To‘lov turi.', max_length=10)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Naqd to‘langan summa.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('card_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Karta orqali to‘langan summa.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Jami to‘langan summa.', max_digits=12)),
                ('note', models.TextField(blank=True, default='', help_text='Qo‘shimcha izoh.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='order_order_order_i_b734e6_idx',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='order_order_order_i_854de1_idx'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(help_text='Qaysi buyurtma uchun to‘lov qilingan.', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='order.order'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type'], name='order_payme_payment_4c04cb_idx'),
        ),
    ]
