# Generated by Django 5.1.7 on 2026-04-03 11:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kategoriya nomi.', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Kategoriya faol yoki nofaol ekanini bildiradi.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Kategoriya yaratilgan vaqt.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Kategoriya oxirgi marta yangilangan vaqt.')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='table_categ_name_c5305f_idx'), models.Index(fields=['is_active'], name='table_categ_is_acti_74903a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Mahsulotning asosiy nomi.', max_length=255)),
                ('kitchen_name', models.CharField(blank=True, default='', help_text='Oshxonada ko‘rinadigan nom. Bo‘sh bo‘lsa name bilan bir xil bo‘ladi.', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Mahsulot narxi.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Mahsulot sotuvda faol yoki yo‘qligi.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Mahsulot yaratilgan vaqt.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Mahsulot oxirgi marta yangilangan vaqt.')),
                ('category', models.ForeignKey(help_text='Mahsulot qaysi kategoriyaga tegishli.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='table.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ins', to='table.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_outs', to='table.product')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Stol nomi yoki raqami. Masalan: 1-stol, VIP-1.', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('free', 'Bo‘sh'), ('busy', 'Band'), ('payment', 'Hisob jarayonida')], default='free', help_text='Stolning joriy holati.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Stol faol yoki nofaol ekanini bildiradi.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Stol yaratilgan vaqt.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Stol oxirgi marta yangilangan vaqt.')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='table_table_name_a29795_idx'), models.Index(fields=['status'], name='table_table_status_bd8660_idx'), models.Index(fields=['is_active'], name='table_table_is_acti_09b1c7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='table_produ_categor_c94c1e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='table_produ_name_d5e829_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='table_produ_is_acti_fdc071_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_product_name_per_category'),
        ),
    ]
